SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_CONFORMIDAD]
AS
SELECT NOMPER,APEPER,DNIPER,NOMCAR,FIRTSCONF,SECONDCONF,THIRDCONF,QUARTERCONFT,FIFTHCONF
FROM CONFORMIDAD
INNER JOIN PERSONA
ON CONFORMIDAD.PERSONA_CODPER = PERSONA.CODPER
INNER JOIN CARRERA
ON PERSONA.CARRERA_CODCAR = CARRERA.CODCAR AND ESTPER='A'
GO
