SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_ORDEN_MERITO]
AS
select VW_RESULTADOS.NOMPER AS ALUMNO,COUNT(VW_RESULTADOS.DNIPER) AS CANTIDAD,SUM(PUNTAJE1+PUNTAJE2+PUNTAJE3+PUNTAJE4+PUNTAJE5+PUNTAJE6) AS PUNTAJE
FROM VW_RESULTADOS
GROUP BY VW_RESULTADOS.NOMPER
GO
