SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_RESULTADOS] AS
 select 
 PERSONA.NOMPER,PERSONA.APEPER,PERSONA.DNIPER,CARRERA.NOMCAR,TIPO_EXAMEN.NOMTIPEXA,FECHORAEXA,HOREXA,RESPUESTAS.RES1,PREGUNTAS.PRE1,RESPUESTAS.RES2,PREGUNTAS.PRE2,RESPUESTAS.RES3,PREGUNTAS.PRE3,RESPUESTAS.RES4,PREGUNTAS.PRE4,RESPUESTAS.RES5,PREGUNTAS.PRE5,RESPUESTAS.RES6,PREGUNTAS.PRE6,
 CASE WHEN RESPUESTAS.RES1 = PREGUNTAS.PRE1 THEN 1
 ELSE 0 END  AS PUNTAJE1,
  CASE WHEN RESPUESTAS.RES2 = PREGUNTAS.PRE2 THEN 1
 ELSE 0 END  AS PUNTAJE2,
   CASE WHEN RESPUESTAS.RES3 = PREGUNTAS.PRE3 THEN 1
 ELSE 0 END  AS PUNTAJE3,
   CASE WHEN RESPUESTAS.RES4 = PREGUNTAS.PRE4 THEN 1
 ELSE 0 END  AS PUNTAJE4,
   CASE WHEN RESPUESTAS.RES5 = PREGUNTAS.PRE5 THEN 1
 ELSE 0 END  AS PUNTAJE5,
   CASE WHEN RESPUESTAS.RES6 = PREGUNTAS.PRE6 THEN 1
 ELSE 0 END  AS PUNTAJE6
 FROM RESPUESTAS
 INNER JOIN PREGUNTAS
 ON  RESPUESTAS.CODPRE = PREGUNTAS.CODPRE
 INNER JOIN PERSONA
 ON RESPUESTAS.CODPER = PERSONA.CODPER
 INNER JOIN CARRERA
 ON PREGUNTAS.CARRERA_CODCAR = CARRERA.CODCAR
 INNER JOIN TIPO_EXAMEN
 ON PREGUNTAS.TIPO_EXAMEN_CODTIPEXA = TIPO_EXAMEN.CODTIPEXA
GO
