CREATE TABLE [dbo].[UBIGEO]
(
[CODUBI] [int] NOT NULL IDENTITY(1, 1),
[DEPUBI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DISUBI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PROUBI] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UBIGEO] ADD CONSTRAINT [PK__UBIGEO__CBDEA16A33834014] PRIMARY KEY CLUSTERED  ([CODUBI]) ON [PRIMARY]
GO
