CREATE TABLE [dbo].[COLEGIO]
(
[CODCOL] [int] NOT NULL IDENTITY(1, 1),
[NOMCOL] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODREFCOL] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ESTCOL] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UBIGEO_CODUBI] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COLEGIO] ADD CONSTRAINT [PK__COLEGIO__CB6EEDF018286ADB] PRIMARY KEY CLUSTERED  ([CODCOL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COLEGIO] ADD CONSTRAINT [COLEGIO_UBIGEO] FOREIGN KEY ([UBIGEO_CODUBI]) REFERENCES [dbo].[UBIGEO] ([CODUBI])
GO
