CREATE TABLE [dbo].[COLEGIO]
(
[CODCOL] [int] NOT NULL,
[NOMCOL] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODREFCOL] [char] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ESTCOL] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
ALTER TABLE [dbo].[COLEGIO] ADD CONSTRAINT [COLEGIO_pk] PRIMARY KEY CLUSTERED  ([CODCOL])
GO
