CREATE TABLE [dbo].[TIPO_EXAMEN]
(
[CODTIPEXA] [int] NOT NULL IDENTITY(1, 1),
[NOMTIPEXA] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TIPO_EXAMEN] ADD CONSTRAINT [PK__TIPO_EXA__595C57FFFBB2624E] PRIMARY KEY CLUSTERED  ([CODTIPEXA]) ON [PRIMARY]
GO
