CREATE TABLE [dbo].[CARRERA]
(
[CODCAR] [int] NOT NULL IDENTITY(1, 1),
[NOMCAR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABRCAR] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ESTCAR] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARRERA] ADD CONSTRAINT [PK__CARRERA__CB56521C3AE7F029] PRIMARY KEY CLUSTERED  ([CODCAR]) ON [PRIMARY]
GO
