CREATE TABLE [dbo].[AULA]
(
[CODAUL] [int] NOT NULL IDENTITY(1, 1),
[NUMAUL] [char] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AFORAUL] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AULA] ADD CONSTRAINT [PK__AULA__CA2972F374504111] PRIMARY KEY CLUSTERED  ([CODAUL]) ON [PRIMARY]
GO
