CREATE TABLE [dbo].[MODALIDAD]
(
[CODMOD] [int] NOT NULL,
[NOMMOD] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ESTMOD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
ALTER TABLE [dbo].[MODALIDAD] ADD CONSTRAINT [MODALIDAD_pk] PRIMARY KEY CLUSTERED  ([CODMOD])
GO
