CREATE TABLE [dbo].[ESTUDIANTE]
(
[CODEST] [int] NOT NULL,
[NOMEST] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APEEST] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNIEST] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CELEST] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIREST] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COREST] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FECNACEST] [date] NOT NULL,
[ESTEST] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODUBI] [char] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
ALTER TABLE [dbo].[ESTUDIANTE] ADD CONSTRAINT [ESTUDIANTE_pk] PRIMARY KEY CLUSTERED  ([CODEST])
GO
ALTER TABLE [dbo].[ESTUDIANTE] ADD CONSTRAINT [ESTUDIANTE_UBIGEO] FOREIGN KEY ([CODUBI]) REFERENCES [dbo].[UBIGEO] ([CODUBI])
GO
