CREATE TABLE [dbo].[HORARIO_EXAMEN]
(
[CODHORAEXA] [int] NOT NULL IDENTITY(1, 1),
[PREGUNTAS_CODPRE] [int] NOT NULL,
[PERSONA_CODPER] [int] NOT NULL,
[AULA_CODAUL] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HORARIO_EXAMEN] ADD CONSTRAINT [PK__HORARIO___970924A55FA05645] PRIMARY KEY CLUSTERED  ([CODHORAEXA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HORARIO_EXAMEN] ADD CONSTRAINT [HORARIO_EXAMEN_AULA] FOREIGN KEY ([AULA_CODAUL]) REFERENCES [dbo].[AULA] ([CODAUL])
GO
ALTER TABLE [dbo].[HORARIO_EXAMEN] ADD CONSTRAINT [HORARIO_EXAMEN_PERSONA] FOREIGN KEY ([PERSONA_CODPER]) REFERENCES [dbo].[PERSONA] ([CODPER])
GO
ALTER TABLE [dbo].[HORARIO_EXAMEN] ADD CONSTRAINT [Table_38_PREGUNTAS] FOREIGN KEY ([PREGUNTAS_CODPRE]) REFERENCES [dbo].[PREGUNTAS] ([CODPRE])
GO
