CREATE TABLE [dbo].[PERSONA]
(
[CODPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[APEPER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DNIPER] [char] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CELPER] [char] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DIRPER] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECNACPER] [date] NOT NULL,
[ESTPER] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TIPPER] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODUBI] [int] NOT NULL,
[COLEGIO_CODCOL] [int] NOT NULL,
[MODALIDAD_CODMOD] [int] NOT NULL,
[CARRERA_CODCAR] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PK__PERSONA__B6D609AB21C8540A] PRIMARY KEY CLUSTERED  ([CODPER]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PERSONA_CARRERA] FOREIGN KEY ([CARRERA_CODCAR]) REFERENCES [dbo].[CARRERA] ([CODCAR])
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PERSONA_COLEGIO] FOREIGN KEY ([COLEGIO_CODCOL]) REFERENCES [dbo].[COLEGIO] ([CODCOL])
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PERSONA_MODALIDAD] FOREIGN KEY ([MODALIDAD_CODMOD]) REFERENCES [dbo].[MODALIDAD] ([CODMOD])
GO
ALTER TABLE [dbo].[PERSONA] ADD CONSTRAINT [PERSONA_UBIGEO] FOREIGN KEY ([CODUBI]) REFERENCES [dbo].[UBIGEO] ([CODUBI])
GO
