CREATE TABLE [dbo].[CARRERA]
(
[CODCAR] [int] NOT NULL,
[NOMCAR] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ABRCAR] [char] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ESTCAR] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
)
GO
ALTER TABLE [dbo].[CARRERA] ADD CONSTRAINT [CARRERA_pk] PRIMARY KEY CLUSTERED  ([CODCAR])
GO
