CREATE TABLE [dbo].[MODALIDAD]
(
[CODMOD] [int] NOT NULL IDENTITY(1, 1),
[NOMMOD] [varchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ESTMOD] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MODALIDAD] ADD CONSTRAINT [PK__MODALIDA__B1E050AADE4062AA] PRIMARY KEY CLUSTERED  ([CODMOD]) ON [PRIMARY]
GO
