CREATE TABLE [dbo].[RESPUESTAS]
(
[CODRES] [int] NOT NULL IDENTITY(1, 1),
[RES1] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES2] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES3] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES4] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES5] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES6] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES7] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES8] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES9] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES10] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES11] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES12] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES13] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES14] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES15] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES16] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES17] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES18] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES19] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES20] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES21] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES22] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES23] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES24] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES25] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES26] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES27] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES28] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES29] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES30] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES31] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES32] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES33] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES34] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES35] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES36] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES37] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES38] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES39] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RES40] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CODPRE] [int] NOT NULL,
[CODPER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESPUESTAS] ADD CONSTRAINT [PK__RESPUEST__B7562DB8A12353FB] PRIMARY KEY CLUSTERED  ([CODRES]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESPUESTAS] ADD CONSTRAINT [RESPUESTAS_PERSONA] FOREIGN KEY ([CODPER]) REFERENCES [dbo].[PERSONA] ([CODPER])
GO
ALTER TABLE [dbo].[RESPUESTAS] ADD CONSTRAINT [RESPUESTAS_PREGUNTAS] FOREIGN KEY ([CODPRE]) REFERENCES [dbo].[PREGUNTAS] ([CODPRE])
GO
